// App


// Navigator
export const KEEP_NAVIGATOR_POSITION = 'KEEP_NAVIGATOR_POSITION';
export const SET_NAVIGATOR_VISITED_LIST = 'SET_NAVIGATOR_VISITED_LIST';
export const SET_NAVIGATOR_VISITED_LAST = 'SET_NAVIGATOR_VISITED_LAST';
